apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-apps
provisioner: k8s-sigs.io/nfs-apps
reclaimPolicy: Delete
parameters:
  archiveOnDelete: "false"
  onDelete: "delete"
# mountOptions:
#   - nfsvers=4.2
#   - noatime
