apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-provisioner-db
  labels:
    app: nfs-provisioner-db
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-provisioner-db
  template:
    metadata:
      labels:
        app: nfs-provisioner-db
    spec:
      serviceAccountName: nfs-client-provisioner
      # imagePullSecrets:
      #   - name: harbor-secret
      containers:
        - name: nfs-client-provisioner
          image: h2372/nfs-subdir-external-provisioner:v1
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            - name: PROVISIONER_NAME
              value: k8s-sigs.io/nfs-db
            - name: NFS_SERVER
              value: 192.168.2.10          # Or 192.168.2.20 for a 2nd NFS server
            - name: NFS_PATH
              value: /data/nfs/database     # Or 2nd path
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.2.10          # Or 192.168.2.20
            path: /data/nfs/database
